### ISSUE TITLE
canto + new website, different search results

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#255] opened 2017-04-11 08:07 UTC
if I enter rpa12 in canto Iget 3 results, but on pombase2 only 1 result
![screen shot 2017-04-11 at 09 05 14](https://cloud.githubusercontent.com/assets/12727506/24898875/39fd9de2-1e96-11e7-8c12-7066cdb24b4a.png)
![screen shot 2017-04-11 at 09 05 00](https://cloud.githubusercontent.com/assets/12727506/24898874/39d50314-1e96-11e7-835f-1af452e064a5.png)

**Comment by kimrutherford** [comment] 2017-04-11 08:21
Oh dear.  That looks like a Canto bug.  Chado has rpa12 as SPCC1259.03 which isn't one of the systematic IDs that Canto suggests.

**Comment by kimrutherford** [comment] 2017-04-11 08:24
And in Chado rpa12 isn't a synonym for any other genes.

**Comment by kimrutherford** [comment] 2017-04-12 06:31
> And in Chado rpa12 isn't a synonym for any other genes.

I've sort-of worked this one out.  rpa12 isn't a synonym for any other genes but rpa1 is.  It looks like the autocomplete got a bit behind your keystrokes (which shouldn't happen) so even though "rpa12" was being shown it was still showing the search results for "rpa1".

So Chado is OK, which is a relief but there is a problem with the autocomplete.

Which browser were you using?  I've tried Chrome and Firefox and I can't reproduce it.

**Comment by Antonialock** [comment] 2017-04-12 08:55
firefox. I think I may have used the"add a gene link" from when you are prompted for the interacting protein for a genetic interaction (either that or I was doing it from the genotype management section)

**Comment by kimrutherford** [comment] 2017-04-19 06:11
> firefox

Sorry, I've tried to reproduce this bug but failed.  Has it happened more than once?

**Comment by Antonialock** [comment] 2017-04-19 07:17
I don't know

**Comment by kimrutherford** [comment] 2017-04-21 09:59
It might have been a temporary network problem.  I think I'll close this since we can't reproduce it.  If you see this again please re-open the ticket.

**Closed by kimrutherford** 2017-04-21 09:59 UTC
Labels: bug, next
