### ISSUE TITLE
allow >1 community curation attribution

### ISSUE THREAD

**Issue by ValWood** [pombase/website#525] opened 2017-09-21 10:18 UTC
For this paper:

~http://pombase-dev.bioinformatics.nz/reference/PMID:26132084~
https://www.pombase.org/reference/PMID:26132084

2 people did CC, in these cased can we attribute both?

**Comment by kimrutherford** [comment] 2021-04-16 05:35
> 2 people did CC, in these cased can we attribute both?

Currently we only export the most recent curator name.  We'll need to change the Canto code to export the names of the previous curators then load them into Chado.  It's not a big job.

**Comment by kimrutherford** [comment] 2021-04-26 07:01
I've started having a look at this.  Do we want to show only curators who have made an annotation?  There a lot of sessions that have been re-assigned before the curator makes any annotation.  And there are sessions like this where all the annotations are by a previous curator and the listed current curator has no annotations:
https://curation.pombase.org/pombe/view/object/curs/5848?model=track
https://curation.pombase.org/pombe/curs/190ddb12f4f3e614/ro/

**Comment by mah11** [comment] 2021-04-26 08:35
> Do we want to show only curators who have made an annotation?

I think so.

**Comment by ValWood** [comment] 2021-04-26 09:23
I agree.

**Comment by kimrutherford** [comment] 2021-04-26 09:43
> > Do we want to show only curators who have made an annotation?
>
> I think so.

What should we do in this case where the assigned curator has no annotations?:
https://curation.pombase.org/pombe/view/object/curs/5848?model=track
https://curation.pombase.org/pombe/curs/190ddb12f4f3e614/ro/

Should we ignore the assigned curator and just check which curators have made an annotation?

**Comment by ValWood** [comment] 2021-04-26 12:19
I think so, but the only complication might be that sometimes we assign a curator so they get attribution for preparing a HTP dataset or browser track data, and then we add a couple of annotations. They would not get attributed in this case. Should we attribute that separately in some way?
 Thursday chat?

**Comment by kimrutherford** [comment] 2021-04-26 12:21
> Thursday chat?

I think that makes sense to make sure I've got things straight before changing anything.

**Comment by ValWood** [comment] 2021-04-29 07:58
> They would not get attributed in this case. Should we attribute that separately in some way?

there are not many examples of this. Maybe we ignore and have a separate way to attribute.

**Comment by ValWood** [comment] 2021-04-29 09:25
Summary
If the session is assign to a community member, they are the community curator
If they did not do any curation, remove them.
If more than one person did curation, attribute both.

Later we would like a way to distinguish LTP from HTP contribution (sometimes we do the HTP)

**Comment by ValWood** [comment] 2021-12-30 16:54
We can discuss this one soon. We will need to do this ticket as part of Apicuron. Probably some of the problem is solved by the new mechanism to attribute the provision of HTP datasets?

**Comment by kimrutherford** [comment] 2022-06-27 08:14
> Summary
> If the session is assign to a community member, they are the community curator
> If they did not do any curation, remove them.
> If more than one person did curation, attribute both.

Does this boil down to?:
  - ignore who the session who assigned to
  - attribute those people who have made at least one annotation
  - if any of the annotations are by community curators then call it a community session

**Comment by kimrutherford** [comment] 2022-07-02 05:36
Hi @jseager7

I'm tagging you because at some point soonish we need to change the Canto JSON format to add a "curators" field.  We can leave the "curator" field in place until we update downstream tools to handle the new field.  So it should be a painless change.

I'm about to transfer this issue to the Canto tracker so sorry if you see this twice.

**Comment by kimrutherford** [comment] 2022-07-02 05:47
> I'm about to transfer this issue to the Canto tracker so sorry if you see this twice.

I changed my mind and made a new issue instead: pombase/canto#2594

This issue can cover the website changes.

**Comment by kimrutherford** [comment] 2022-07-08 10:50
This is done:
  - pombase/canto#2594

Next step:
  - pombase/pombase-chado#991

**Comment by kimrutherford** [comment] 2022-08-13 05:57
That's done for tonight's load so PMID:26132084 should look like this on Sunday:

![image](https://user-images.githubusercontent.com/90474/184470703-eb3eae29-9c6c-4e1b-b1c6-5ba353c0a737.png)


The ORCID of the curators is now available in Chado too so it will be easy to make a file for updating Apicuron.

**Comment by kimrutherford** [comment] 2022-08-14 05:46
> That's done for tonight's load so PMID:26132084 should look like this on Sunday:

The load failed because there was a problem with downloading the latest biogrid.  So I'll check things on Monday morning instead.

**Comment by kimrutherford** [comment] 2022-08-15 03:55
The publication pages now show all the community curators from Canto.

> but the only complication might be that sometimes we assign a curator so they get attribution for preparing a HTP dataset or browser track data, and then we add a couple of annotations. They would not get attributed in this case. Should we attribute that separately in some way?

That case isn't handled yet.

**Comment by ValWood** [comment] 2022-08-17 17:19
Excellent!

**Comment by kimrutherford** [comment] 2023-10-09 03:39
> I think so, but the only complication might be that sometimes we assign a curator so they get attribution for preparing a HTP dataset or browser track data, and then we add a couple of annotations. They would not get attributed in this case. Should we attribute that separately in some way?

Would something like this make sense on pombase.org?:

![image](https://github.com/pombase/website/assets/90474/a24182c6-a7a6-480b-a4b7-5fd4efbf722d)

For APICURON we could have two different categories ("terms") so that Canto curation and providing a dataset look different on the ORCID page.  Or, alternatively, if someone provides a dataset they are added as a community curator for the paper.  So just treat providing a dataset as a type of community curation.

**Comment by ValWood** [comment] 2023-10-09 09:46
That would work!

**Comment by kimrutherford** [comment] 2023-10-10 07:30
> Would something like this make sense on pombase.org?:

See also: https://github.com/pombase/pombase-chado/issues/886#issuecomment-1640124903

**Comment by kimrutherford** [comment] 2023-10-17 06:54
Of all goes well, on Wednesday morning we'll have attribution for PHAF datasets on pombase.org, like:
```
High-throughput dataset provided by Li-Lin Du
```
For now, if a staff curator prepared the dataset there won't be a message.

**Comment by kimrutherford** [comment] 2023-10-19 07:59
> Of all goes well, on Wednesday morning we'll have attribution for PHAF datasets on pombase.org

Done!  Although we should chat about the wording some time.

https://www.pombase.org/reference/PMID:26791325

![image](https://github.com/pombase/website/assets/90474/e98191d1-92f0-47c7-a979-49731a78e880)

**Comment by kimrutherford** [comment] 2023-10-20 08:26
We also need to think about what to do with cases like this: https://www.pombase.org/reference/PMID:26791325
It says "Curated by PomBase staff" but all the curation comes from the PHAF file provided by the community curator.

I think the logic needs a bit of tweaking in those cases.

Also for [PMID:27887640](https://www.pombase.org/reference/PMID:27887640) we don't show the attribution for the PHAF file provided by the user:
![image](https://github.com/pombase/website/assets/90474/faf1ca94-9cd4-4c5c-ab5f-727be631309a)

But for [PMID:27558664](https://www.pombase.org/reference/PMID:27558664) we do show the attribution even though it's the same situation:
![image](https://github.com/pombase/website/assets/90474/3c2ec585-555e-457e-b7ac-83cb0ef8f6c2)

There's a bugsomewhere.  :-)

**Comment by kimrutherford** [comment] 2023-10-23 03:04
> It says "Curated by PomBase staff" but all the curation comes from the PHAF file provided by the community curator.

That's fixed now so it doesn't mention PomBase staff in those cases.

> Also for PMID:27887640 we don't show the attribution for the PHAF file provided by the user:
> ...
> But for PMID:27558664 we do show the attribution even though it's the same situation:
> ...
> There's a bug somewhere. :-)

I wasn't able to reproduce this even though I have screenshots of the problem.  I suspect it was a temporary local problem on my development version.  So I'll close this until we see the problem again.

**Closed by kimrutherford** 2023-10-23 03:04 UTC
Labels: publication pages, high priority, apicuron
