### ISSUE TITLE
advanced query, slow

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1440] opened 2019-12-10 13:42 UTC
Has anyone else noticed this. For a week or so it seems to be very slow for me. The autocomplete seems to take forever (to the point where I think it isn't working), and then the list takes ages to appear after submission. I thought for a while it might be my connection, but it is the same at home, in the department, at my mums.

I think it has been like this for a week or 2. Did something change?
Has anyone else noticed anything?

**Comment by mah11** [comment] 2019-12-10 13:50
it's fine for me in the office
will check at home later

**Comment by kimrutherford** [comment] 2019-12-11 11:56
I'm not having any problems from NZ.  I've checked the server and it all seems OK.  Babraham had a network glitch today so maybe they've been having other problems.  Could you let me know if you spot any slowdowns during the rest of the week?

**Comment by mah11** [comment] 2019-12-11 11:58
oh yeah, forgot to mention - I checked at home yesterday (late afternoon) and it was fine there too

**Comment by ValWood** [comment] 2019-12-19 08:31
For me, if I type something int the autocomplete, it does not seem to work immediately. I need to delete it and start retyping and then it works. At first, I thought a certain number of characters were required but it's the same if I begin with a long or short string.
It seems to happen wherever `I am and whichever laptop I use...(Chrome on both)

**Comment by mah11** [comment] 2019-12-19 11:25
still working for me on all sorts of combinations (office: wired connection, desktop, Firefox or Safari; home: wireless, Firefox or Chrome on Linux desktop or Mac laptop) ... I hadn't tested Chrome before today but it's fine too ... (un)lucky you!

**Comment by ValWood** [comment] 2019-12-19 18:02
OK. Appears to be just poor wifi connections

**Comment by ValWood** [comment] 2020-01-03 18:28
This is really weird. I don't think it is my wifi because no other site is affected.

I have not been able to get the lucene search to work all afternoon. However, it did work if I ran a "canned query" first. After running a canned query (or nother query that doesn't require lucene) , and returning to GO or FYPO, the autocomplete works just fine. 

I tired on my other laptop and got the same.

I noticed this before. It seemed to work immediately if I did a different query.
Any ideas?

**Comment by kimrutherford** [comment] 2020-01-04 03:10
I don't have any idea what's going on.  Perhaps the next time you see it, email me straight away and I'll check the server then (if I'm awake)?  Also we could hop on Skype and try to debug it using screen sharing.  I've never noticed a problem from NZ but I don't use the site much.

**Comment by ValWood** [comment] 2020-01-04 09:52
will do...

**Comment by kimrutherford** [comment] 2020-02-14 05:00
We looked at this on Skype and it seems that the slow down is caused by long history lists.  Each query in the history needs to be executed to find if the result count is out of date.  It was firing off 10 queries a second and that was too much work for the browser (and/or the query builder).

I've changed the code to run the queries for the first 10 history items quite quickly (5 per second) and then the rest are updated more slowly (2 per second).  I hope that's a good compromise.

Val could you let me know if that help with that slowness?

**Comment by ValWood** [comment] 2020-02-14 12:42
It seems to be an improvement!  The autocomplete is working for me again.

**Comment by kimrutherford** [comment] 2020-02-24 00:23
Let's close this and open a new issue if it comes back.

**Closed by kimrutherford** 2020-02-24 00:23 UTC
Labels: search

**Comment by ValWood** [comment] 2020-02-24 09:56
Yes, it is *tonnes* better
