### ISSUE TITLE
Display of modified forms in GO extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1710] opened 2021-06-02 13:17 UTC
Example 1, clr4 https://www.pombase.org/gene/SPBC428.08c

<img width="1070" alt="substrate" src="https://user-images.githubusercontent.com/7359272/120486326-d88f6700-c3ac-11eb-9bc8-99ff97aa9a48.png">

has substrate hht1/InitMet-/Ubiq:(K14)

here we display and link to only the modified form.
We also need a link that goes directly to the hht1 PomBase page.

**Comment by ValWood** [comment] 2021-06-02 13:23
Example2: swi6 https://www.pombase.org/gene/SPAC664.01c
If an annotation is a "binding" annotation,  with IPI evidence, it  is displayed like this:

binds&nbsp;hht1&nbsp;(hht1/InitMet-/Me:(K9))
i.e. the "with" field is repurposed to provide a gene page link:

if the evidence is IDA it's displayed like this:
binds hht1/InitMet-/Me:(K9)

<img width="479" alt="Screenshot 2021-06-02 at 14 20 15" src="https://user-images.githubusercontent.com/7359272/120487199-a8949380-c3ad-11eb-9071-6e86bbadd3bb.png">

Do we want  to use this   gene (modified form) format throughout?

**Comment by ValWood** [comment] 2021-06-02 13:32
Note that this would not be necessary for any gene product "active form"   on the gene page 
like hht1 here:

<img width="1001" alt="hht1" src="https://user-images.githubusercontent.com/7359272/120489158-4fc5fa80-c3af-11eb-82f9-7d8805fecddd.png">



 (because 'active form' is only used on the page of the

**Comment by ValWood** [comment] 2021-06-02 14:35
Another consideration:
nuf2 https://www.pombase.org/gene/SPAC27F1.04c

<img width="954" alt="Screenshot 2021-06-02 at 15 33 01" src="https://user-images.githubusercontent.com/7359272/120499495-04fcb080-c3b8-11eb-80e5-92fd13b29f64.png">

 in Canto:
<img width="745" alt="? substrate and modified form" src="https://user-images.githubusercontent.com/7359272/120499554-12b23600-c3b8-11eb-904f-f4d78e6657c1.png">

here, I added both the substrate and the modified form.

I guess both need not be added, but if they are they should be displayed as above  (od however we decide) rather than separate entities.

**Comment by kimrutherford** [comment] 2021-06-25 04:26
> Do we want to use this gene (modified form) format throughout?

That makes sense but that gene ID isn't included in the extension in all these cases is it?  I'm uneasy about trying to parse the gene name from the PRO term name as that seems a dodgy.  Can we include the gene ID in the extension or in the PRO term definition?

**Comment by ValWood** [comment] 2021-06-25 08:09
The systematic IDs don't seem to be included in PRO which is a shame

pombe_mini_PR.obo 

id: PR:000044702
name: histone H3.2, initiator methionine removed K9-trimethylated form (Schizosaccharomyces pombe)
def: "A histone H3.2, initiator methionine removed K9-methylated form (Schizosaccharomyces pombe) whose methylation type is trimethylation. Example: UniProtKB:P09988-1, 2-136, Lys-10, MOD:00083." [PMID:23849629, PRO:DAN]
comment: Category=organism-modification. Requested by=PomBase. Note that in the article cited residue number is different because the initial methionine is not counted.
synonym: "Spom-hht2/InitMet-/K9me3" EXACT PRO-short-label [PRO:DAN]
is_a: PR:000027593 ! histone H3.2, initiator methionine removed K9-methylated form (Schizosaccharomyces pombe)


We could use the UniProt IDs, maybe? and map over.
However, using the gene name is fairly  safe, because the genes  with this level of study are not going to have a name change-also Midori crafts these. 

We should probably have a list somewhere of  a procedure things to review in the rare event that an established name changes:
Modification labels.
HTP datasets
Browser metadata etc. 

because problems would not be  confined to PRO labels

**Comment by mah11** [comment] 2021-06-25 10:15
> I'm uneasy about trying to parse the gene name from the PRO term name as that seems a dodgy. 

Your instincts are sound. PRO term names do not necessarily include any gene name at all, and the ones that are included aren't in a nice reproducible position within the string.

> Can we include the gene ID in the extension 

Not sure what you mean here ... would we have to make two extensions, one for the gene and one for the protein isoform? That feels redundant.

> or in the PRO term definition?

I would very much love to get through this life without having to edit PRO term definitions, either locally or by making requests to PRO. It seems like it wouldn't always be easy to parse the correct gene name from a text definition anyway -- at present they even sometimes mention the (different) names of orthologs in other species, with or without also including the pombe name. So no.

The closest-to-simple fix would be to use the synonyms of type `PomBase_display_name` (it's these, not gene names, that I "craft" per Val's comment) from the mini-PRO file. Almost all of them are in a parsing-friendly format where the gene name is the text at the beginning of the synonym string, up to but not including the `/` (there are 5 exceptions at present, listed below). If that's promising, we could have log warnings for any PRO terms we use anywhere that don't have a PomBase_display_name set.

non-exceptional example:
synonym: "cdc2/Phos:(Y15,T167)" EXACT PomBase_display_name [PomBase:curators]

-----

the exceptions:

id: PR:000025001
name: M-factor
synonym: "mature M-factor" EXACT PomBase_display_name [PomBase:curators]

id: PR:000028943
name: peptide methionine sulfoxide reductase reduced form (Schizosaccharomyces pombe)
synonym: "MSRA/Red+" EXACT PomBase_display_name [PomBase:curators]

id: PR:000028945
name: peptide methionine sulfoxide reductase oxidized form (Schizosaccharomyces pombe)
synonym: "MSRA/Ox+" EXACT PomBase_display_name [PomBase:curators]

id: PR:000046671
name: transcription factor sre2, Sre2P form (Schizosaccharomyces pombe)
synonym: "Sre2P" EXACT PomBase_display_name [PomBase:curators]

id: PR:000046672
name: transcription factor sre2, Sre2N form (Schizosaccharomyces pombe)
synonym: "Sre2N" EXACT PomBase_display_name [PomBase:curators]

**Comment by ValWood** [comment] 2021-12-21 17:45
Here is another example
<img width="553" alt="example of PRO substrate" src="https://user-images.githubusercontent.com/7359272/146975051-f71cf8e0-ac21-4e11-9e85-50e12baaed65.png">
I will need a list of any with this 'dual annotation' to fix.

**Comment by kimrutherford** [comment] 2022-04-03 20:35
Midori added the gene IDs to the OBO file (pombe-embl/mini-ontologies/pombe_mini_PR.obo) a while ago.  I've now changed the OBO reading code so that it can parse and store the gene IDs in Chado.

That means we can now add a link to the gene anywhere on the site where there is a pombe PR ID.

We should have a chat about this issue once there is less going on.

**Comment by kimrutherford** [comment] 2022-04-04 07:10
I changed the web site code to add the gene information from Chado where the PR terms are displayed.  It looks better now (SPBC428.08c: https://desktop.kmr.nz/gene/SPBC428.08c).  I won't release the changes yet because there is still a bug to fix.

![gene-pr-after-1](https://user-images.githubusercontent.com/90474/161490880-04e1fe6c-9262-4c67-a258-4a6346103f4b.png)

**Comment by ValWood** [comment] 2022-04-04 08:10
So you just need to switch the ID for the display substrate?

[hht1/InitMet-/Ubiq:(K14)](https://proconsortium.org/app/entry/PR:000050217)

After we display like this, I am wondering if I should edigt the display substrates to InitMet-/Ubiq:(K14)?

**Comment by kimrutherford** [comment] 2022-04-04 08:19
> So you just need to switch the ID for the display substrate?

It was working better earlier.  :-)  I didn't notice that I broke it before the screenshot.

**Comment by kimrutherford** [comment] 2022-04-06 06:27
> I didn't notice that I broke it before the screenshot.

I've improved it a bit today.  This change is only on my desktop for now.  I going to review it when my brain is less fuzzy.  Next step is remove the gene name from the PR term name when it's redundant.  And I'll fix it so that it doesn't say "binds hht1 binds hht1".

![gene-pr-2](https://user-images.githubusercontent.com/90474/161908181-8bfc8cd0-00f7-4df7-8990-7317a7e8cd2a.png)

**Comment by ValWood** [comment] 2022-04-06 07:31
baby steps  ;) looking good so far.

**Comment by kimrutherford** [comment] 2022-04-07 04:31
It's getting there.  Here's how the swi6 MF summary looks now on my desktop (https://desktop.kmr.nz/gene/SPAC664.01c):

![gene-pr-1](https://user-images.githubusercontent.com/90474/162119940-5b46db50-1d50-45d9-98b2-7233c3f0fa65.png)

Now that the duplicate "binds hht1" is gone, three more annotations are hidden in the summary than currently.

Do you think the "InitMet-/Me:(K9)" should still be in brackets after this change?  Would "hht1 /InitMet-/Me:(K9)" be better, with the appropriate bits as separate links?

Here's the detailed view:

![gene-pr-2](https://user-images.githubusercontent.com/90474/162120051-6715a3bb-8f89-46a1-bb57-dbf39240c259.png)

I should be able to tidy this up and commit the changes for Thursday night's load.

**Comment by kimrutherford** [comment] 2022-04-07 05:57
All the changes are checked in now.  It should be on the main site on Friday morning.

**Comment by ValWood** [comment] 2022-04-08 09:38
Looks good.

>Do you think the "InitMet-/Me:(K9)" should still be in brackets after this change? Would "hht1 /InitMet-/Me:(K9)" be better, with the appropriate bits as separate links?

I'm not sure.
At least with  the brackets it is clearer that they are separate.  Let's keep them for now.
We could ask on a group call for opinions.

**Comment by kimrutherford** [comment] 2022-04-08 09:48
> At least with the brackets it is clearer that they are separate. Let's keep them for now.
> We could ask on a group call for opinions.

OK.

> Note that this would not be necessary for any gene product "active form" on the gene page
like hht1 here:
> <img width="1001" alt="hht1" src="https://user-images.githubusercontent.com/7359272/120489158-4fc5fa80-c3af-11eb-82f9-7d8805fecddd.png">

That now looks like this.  Is that OK?:

![hht1-1](https://user-images.githubusercontent.com/90474/162411148-d19bf4e5-fde5-4cde-b23c-a58abedf0862.png)

**Comment by ValWood** [comment] 2022-04-08 09:56
> That now looks like this. Is that OK?:

perfect, that's much more human readable.I think I request this change in another ticket.

**Comment by ValWood** [comment] 2022-04-08 09:57
...the ordering that is, makes sense not to link.

**Closed** 2022-04-11 01:02 UTC
Labels: display, filtering_and_extensions
