### ISSUE TITLE
list upload (advanced search)

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1609] opened 2020-09-18 08:04 UTC
I found myself wanting to do a search for

GO term1 NOT (term1,2,3,4,5,6,7,8,9,10,11,12,13,14...)

I have term 1-14 in a list already, but I don't fancy loading them in one by one.

Would it be possible to expand gene list upload to include other identifiers? (GO in this case, maybe it would be useful with FYPO for other users?)

**Comment by ValWood** [comment] 2020-09-18 09:12
Just union lists 1-14, and then subtract them from  your list of interest?

**Comment by Antonialock** [comment] 2020-09-18 09:18
would I have to make 14 separate searches to obtain lists 1-14, bewfore doing the uion?

**Comment by ValWood** [comment] 2020-09-18 09:43
Oh yes. But I thought you said you already had those.
It will only take about 30 seconds ;)  Would it save that much time?
I do it this way all the time....

**Comment by Antonialock** [comment] 2020-09-20 20:24
maybe not....it's just clunky

**Comment by mah11** [comment] 2020-09-24 15:42
the problem isn't the time; it's the 14 extra clicks :P

**Comment by ValWood** [comment] 2020-11-26 22:03
I'm going to close this unless we get a user request...it would be quite a bit of work, and once you have the list you can keep it in your history?

**Closed by ValWood** 2020-11-26 22:03 UTC

**Comment by ValWood** [comment] 2020-11-26 22:05
Mainly closing because it would require  big code changes. Lists are gene-based not term based. I guess a list could be generated for a compound list of terms, but it would be difficult to explain the action in the current interface

**Comment by Antonialock** [comment] 2020-11-27 17:46
I'd argue I AM a user request ;) but fine, I'm an edge case.

PomBase is the gold standard MOD for fungi - a shame it doesn't cover all things fungal biology.
I know I'm biased but I use it all the time as the most trust worthy source

**Comment by Antonialock** [comment] 2020-11-27 17:49
a shame there isn't a well-curated fungi-wide resource...

**Comment by ValWood** [comment] 2020-11-27 20:20
well I can put this ticket as "future" but as it is possible with a little effort it is unlikely to be done  because it will probably take longer to implement than the time it would save --unless you were constantly  using huge list of GO IDs (but then you would keep them in your query history?
I would rather developer time was spent on things that benefit MORE users, or improve the data (QC) , or  improve the workflow substantially. We have to balance how much time this would save, we can't do everything...

**Comment by ValWood** [comment] 2020-11-27 20:22
i.e constant tasks take precedent over one-off tasks.

**Comment by Antonialock** [comment] 2020-11-27 20:53
thanks, I'll holler if it becomes a super valuable exercise in multiple instances ;)
