### ISSUE TITLE
change label for CDS coordinates

### ISSUE THREAD

**Issue by mah11** [pombase/website#59] opened 2016-08-19 15:40 UTC
To avoid confusion about the original meaning (and any other interpretations, correct or incorrect) of "CDS", change the label to "start and end coordinates". Even if "CDS" would be technically correct, enough people don't realize it so changing to something ploddingly unambiguous won't go wrong.

**Comment by kimrutherford** [comment] 2017-05-25 23:51
I guess this is from V1?

Currently in V2 we just have "II, 1500197-1502095 (1899nt)" with no CDS bit.

Would "start and end *translation* coordinates" be clearer?

**Comment by ValWood** [comment] 2017-05-26 09:56
Hmm, I  still think CDS is the correct way to refer to the coding sequence genome coordinates.

The problem is that  people (incorrectly IMHO)  are expecting the number 1899nt to represent the translation lenght. However it does't if it's the start and end of a spliced gene *in the genome*.

The CDS length (or the number we report) is the  entire length of the coding sequence with introns in the genome, and I think that is correct. 

The problem is how to explain this.....

**Comment by ValWood** [comment] 2017-05-26 10:02
Maybe it should be the translated length in nucleotides. I think the meaning has changed over time. it used to be "from coding DNA sequence", which to me would make the CDS length the start and end of the CDS in the DNA not the start and end of the edited sequence.

The edited sequence seems to be what people expect. So we could report the nucleotide length of the translation in  this case....

**Comment by ValWood** [comment] 2017-06-01 10:53
Genomic location	II, 1500197-1502095 (1899nt) start to stop
Genomic location	II, 1500197-1502095 (1899nt) plus UTRs

**Comment by ValWood** [comment] 2017-07-12 22:31
I removed the milestone as I con't imagine it will impede anyone.

**Comment by ValWood** [comment] 2017-10-28 23:20
So here we just need text changes? If so could you provide suitable? @mah11

**Comment by mah11** [comment] 2017-10-30 11:45
If we just stick with the current single set of coordinates, its current label ("genomic location") is fine. If you want to show with and without UTRs, the version from Jun 1 above (https://github.com/pombase/website/issues/59#issuecomment-305459606) would do.

**Comment by ValWood** [comment] 2017-11-02 10:38
Removed discuss label.
 
Just need to add CDS start and end coordinates.

**Comment by kimrutherford** [comment] 2017-11-03 06:06
What text should we have for RNA genes and pseudogenes?

**Comment by kimrutherford** [comment] 2017-11-03 07:05
> What text should we have for RNA genes and pseudogenes?

III, 	2111204-2116520 (5317nt)

**Comment by kimrutherford** [comment] 2017-11-03 07:07
> III, 2111204-2116520 (5317nt)

Sorry, hit submit too soon.  For now I've implemented it like "III, 2111204-2116520 (5317nt)" for genes without a translation, which is what we have at the moment.  Is that enough in that case?

**Comment by kimrutherford** [comment] 2017-11-03 08:36
>  For now I've implemented it like ...

It's on the main site now.  Is it OK?

**Comment by ValWood** [comment] 2017-11-03 11:33
it looks a bit odd, but I think it is clear what it means

Maybe we could say

(CDS start/end)

and 
(+UTRs)

to make  the text shorter.

**Comment by ValWood** [comment] 2017-11-03 16:16
Is my suggestion naff?

**Comment by ValWood** [comment] 2017-11-03 17:25
I think it would be clear to users . They all (should) know what a UTR and a CDS are...

**Comment by Antonialock** [comment] 2017-11-03 18:24
well it is the CDS that's confusing? You said it is the "coding sequence genome coordinates" but according to HGVN +1 is assigned to translation initiation codon in the CDS. What you are talking about is the "genomic reference sequence"?

**Comment by ValWood** [comment] 2017-11-03 18:55
Its the genomic location of the CDS  though?

I still maintain that CDS was "invented" to describe the genomic location in an  EMBL/Genbank  file, 
so its the coordinates of the coding sequence in whichever sequence you are referring to.
i.e the genome here:

FT   CDS             complement(23589..23978)

**Comment by Antonialock** [comment] 2017-11-03 21:42
well yeah, but according to the site I linked to, different people use the term differently, which is why I find it confusing.

**Comment by ValWood** [comment] 2017-11-04 09:03
but what else could it mean in the context we are using it above?

**Comment by ValWood** [comment] 2018-02-27 16:03
I think it's OK to close.

**Closed** 2018-02-27 16:03 UTC
Labels: curators discuss, gene page, quick
