### ISSUE TITLE
missing GO annotation SPCC16A11.07 GO:0140104

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2209] opened 2024-08-12 15:42 UTC
PomBase	SPCC16A11.07			GO:0140104	GO_REF:0000024	ISO	SGD:S000005368	F	XXX		protein	taxon:4896	20240505	PomBase	has_input(CHEBI:46245)	

I can see this annotation in AmiGO
https://amigo.geneontology.org/amigo/gene_product/PomBase:SPCC16A11.07

but not in PomBase?

**Comment by kimrutherford** [comment] 2024-08-12 20:18
Hi Val.

I think it's probably caused by this line in the `legacy_go_from_contigs` log file:

```
line 186: can't find term with ID: CHEBI:46245
```

https://curation.pombase.org/dumps/builds/pombase-build-2024-08-12/logs/log.2024-08-11-21-04-54.legacy_go_from_contigs

I've added `CHEBI:46245` to `pombe-embl/mini-ontologies/chebi.obo` so it should be OK in the morning.

> I can see this annotation in AmiGO

I think that's a different annotation: `has_input(CHEBI:52971)` instead of `has_input(CHEBI:46245)`.

**Comment by kimrutherford** [comment] 2024-08-13 01:02
> so it should be OK in the morning

Fixed now.  https://desktop.kmr.nz/gene/SPCC16A11.07

**Closed by kimrutherford** 2024-08-13 01:02 UTC
Labels: needs checking

**Comment by ValWood** [comment] 2024-08-13 06:33
Thanks for figuring that one out!
