### ISSUE TITLE
Should we have a separate MF phenotype section (was "missing phenotypes")

### ISSUE THREAD

**Issue by ValWood** [pombase/website#259] opened 2017-04-13 08:50 UTC
I notice that I can't see any  decreased protein-protein interaction phenotypes...

I think this is likely becase we are only showing phenotypes which match one of the filters
and these don't currently?

see cdc2
![missing](https://cloud.githubusercontent.com/assets/7359272/24997437/8dc21a9a-202e-11e7-9658-0e3bebd75da7.jpg)

**Comment by ValWood** [comment] 2017-04-13 08:52
I think we could add  "protein interaction phenotype"  and "abnormal catalytic activity" to the filter

but the "no filter" option should still show everything regardless.

**Comment by kimrutherford** [comment] 2017-04-13 09:42
Yep, that odd.  I don't think it's the filtering because the "no filter" options just shows the full table.  I'll investigate.

**Comment by kimrutherford** [comment] 2017-04-13 09:59
It looks like the problem is that "protein interaction phenotype"  isn't a child of "Population phenotype" or "Cell phenotype" so isn't displayed in either section.  Does that make sense?  If that is the problem it can be fixed by changing the configuration.

**Comment by kimrutherford** [comment] 2017-04-13 10:37
> I think we could add "protein interaction phenotype" and "abnormal catalytic activity" to the filter

"abnormal catalytic activity" is FYPO:0000661 so that's easy to add.

For "protein interaction phenotype" should we use FYPO:0000702, "protein-protein interaction phenotype"?  Which of the two phrases should be displayed to the user, "Protein .. " or "Protein-protein ..."?

**Comment by kimrutherford** [comment] 2017-04-13 10:46
I've added "Abnormal catalytic activity" and "Protein-protein interaction" for now.  Easy to change the titles in the menu later.

**Comment by mah11** [comment] 2017-04-13 10:49
> "protein[-protein] interaction phenotype" isn't a child of "Population phenotype" or "Cell phenotype" so isn't displayed in either section. Does that make sense?

Yes - "protein-protein interaction phenotype" is in the molecular function phenotype branch. In legacy PomBase we lumped MF phenotypes together with cell phenotypes, and I guess everyone will want to do the same in shiny new PomBase. The broadest MF phenotype term is FYPO:0000652.

> Which of the two phrases should be displayed to the user, "Protein .. " or "Protein-protein ..."?

The FYPO:0000702 term name is "protein-protein interaction phenotype", so I'd use that for filtering (fine to leave off "phenotype", i.e. what you did is good). I think if we do count MF phenotypes as honorary cell phenotypes, that should take care of getting the interaction (and DNA or RNA binding) phenotypes to show up in the complete unfiltered list.

**Comment by kimrutherford** [comment] 2017-04-13 10:57
> we lumped MF phenotypes together with cell phenotypes, and I guess everyone will want to do the same in shiny new PomBase

It would be very easy to have a separate "Molecular function phenotypes" section if that made sense.  It's also easy to add the MF ones into the cell phenotypes.  Which is best?

**Comment by mah11** [comment] 2017-04-13 10:59
I don't have a strong preference, but if it's easy to split out MF phenotypes I see no reason not to do it.

**Comment by mah11** [comment] 2017-04-13 11:00
... probably best to give V&A time to chime in, too

**Comment by kimrutherford** [comment] 2017-04-13 14:07
I've just added "Molecular function phenotype" as a test to make sure that Val's missing annotation appears (it does).  I can leave it as is or merge with the cell phenotypes.

The term page does something sensible now too:
  http://pombase2.bioinformatics.nz/term/FYPO%3A0001645
(it was blank before I added the MF section)

**Comment by mah11** [comment] 2017-04-13 14:11
Isn't it the middle of the night there?

Anyway, I have no objection to having a separate "molecular function phenotype" section, so let's see if V&A like it.

If we do keep MF and cell phenotypes split, we should redo the filter configuration so that the dropdowns only offer relevant selections (no "catalytic activity" in cell or population; no "morphology" in MF, etc.).

**Comment by kimrutherford** [comment] 2017-04-13 22:04
> If we do keep MF and cell phenotypes split, we should redo the filter configuration so that the dropdowns
> only offer relevant selections (no "catalytic activity" in cell or population; no "morphology" in MF, etc.).

No problem, we can do that.

**Comment by ValWood** [comment] 2017-04-14 07:25
I'm not sure.  I  don't think users have any issue considering a MF phenotype as a cell level phenotype. 

Adding another section  will make it easier to miss (I  worry a little that non-familiar users might not even  see 'cellular phenotypes') . Its easy not to see the MF phenotypes on the cdc2 page if you don't know that they are there.

I think there is  also value in keeping these (cellular and MF) together so you can see, for example, all abnormal cell level & molecular phenotypes together without the need to go to 2 separate page sections.

I don't see the value of the spit here as much as for cellular vs population, where it is more important to alert users to the different terms for cell level and population level viability annotation (This is probably the main reason to retain this particular split rather than lump everything)....for cellular/MF here the filters will do the job.

I think we are still considering lumping everything  (moving away from separate sections) and having population and cellular in filters too but probably need to get feedback on this change once we have had the filters in action for a while.

@Antonialock   thoughts?
Maybe if unsure, we keep as is for the time being and you could see if members of Jurg's lab are seeing the MF section.

**Comment by kimrutherford** [comment] 2017-04-14 07:40
> Maybe if unsure, we keep as is for the time being and you could see if members of Jurg's lab are seeing the MF section.

OK, I'll leave this open for a bit while you consider.  I've changed the issue title to make more sense.

**Comment by Antonialock** [comment] 2017-04-17 19:27
I think I think it is neater to split (esp for pages testing a lot of
different constructs) but as you pointed out it might make it easier to
miss the section completely. We can also filter phenitypes now so many
constructs isn't a visual issue...
-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by Antonialock** [comment] 2017-04-17 19:34
In a way I like to split because you answer different questions (usually?)
I.e molecular function phenotype dissect what parts of a protein are
critical for activity, binding etc whereas cell phenotypes are broader
stuff.

...but then I suppose it would also make sense to split out morphology
phenotypes from process phenotypes from localisation phenotypes....maybe
just filtering is the way forward...
-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by ValWood** [comment] 2017-04-19 14:24
Are we sure about this. I didn't know it had been implemented but I only just saw the molecular phenotypes section.
I still think I prefer these groups with cell level phenotypes and handled by the filter, much more difficult to miss...

**Comment by mah11** [comment] 2017-04-19 14:30
It's a trade-off. With MF and cell phenotypes lumped, there's no MF phenotype section to overlook, but there also isn't an immediate indication that they _are_ phenotypes that specifically affect molecular functions.

I kind of like the split, but I know that's because I'm all ontology-oriented so I appreciate the consistency with top-level FYPO organization, and with the reality that binding and catalytic events are molecular-level, not cell-level, phenomena. I don't know what would actually work best for not-professional-curator-or-ontologist users.

**Comment by ValWood** [comment] 2017-04-29 16:24
We still didn't decide what to do here.
I'm still concerned that they will be overlooked.

We could decide later whether to merge them, but as the MF phenotype section is usually very short maybe it could go above the cellular phenotypes.

In the P1 we had
Single-allele:
Population
Cell
Multi-allele:
Population
Cell

but here  it is very  easy not to see  even the cell phenotypes sometimes.

**Comment by kimrutherford** [comment] 2017-05-02 02:07
> I'm still concerned that they will be overlooked.

Won't those annotations be more likely to be overlooked if they in the middle of a bigger table?

> but here it is very easy not to see even the cell phenotypes sometimes.

I don't understand how it could be missed.  Is it hard to see the multi-allele section?  Isn't that the same problem?

**Comment by ValWood** [comment] 2017-05-02 08:49
The multi allele section is easier  locate because it has a direct menu link....
(also people use single gene phenotypes more in the first instance).

I thought the molecular phenotypes should come before cell phenotypes because,  both the population, and molecular are usually quite short then you get the (often) really, really long cellular phenotypes.

I still think that really it would be better to combine molecular and cellular for display even though it isn't strictly ontologically correct. I think the important distinction for users is population level vs. cell level....
and "molecular phenotype" dealt with by a filter....
Would definitely be harder to miss. The molecular phenotypes are important because these usually come when the Gene product is really beginning to be dissected functionality so its a shame for them to be so hidden...

In fact, lets do this..... We can reconsider  to split it out again some time if we have some 
"section summary" type thing later and we can make it clear there are three tables lurking under here......

**Comment by ValWood** [comment] 2017-05-04 10:20
implement as short term and discuss later...

**Comment by kimrutherford** [comment] 2017-05-05 04:41
> In fact, lets do this..

Done!

**Closed by kimrutherford** 2017-05-05 04:41 UTC
Labels: display, gene page, phenotype data

**Comment by ValWood** [comment] 2017-05-05 05:46
yep, much harder to miss...
