### ISSUE TITLE
Add "Priority Unstudied Genes" status page to PomBase v2

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#334] opened 2017-05-15 06:30 UTC
Move this table to v2:
http://www.pombase.org/status/priority-unstudied-genes

**Comment by ValWood** [comment] 2017-05-15 10:55
https://github.com/pombase/website/issues/242

**Comment by ValWood** [comment] 2017-05-25 12:14
seems quick?

**Comment by ValWood** [comment] 2017-05-25 12:17
duplicate of
https://github.com/pombase/website/issues/242

**Closed by ValWood** 2017-05-25 12:17 UTC
Labels: documentation
