### ISSUE TITLE
curation not displaying

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1727] opened 2021-07-20 16:44 UTC
/controlled_curation="term=misc, longer transcript expressed during cold shock due to altered 3'-end processing; db_xref=PMID:8493104; date=20140814"
these are not displaying for fib1

/controlled_curation="term=orthologous to S. cerevisiae YDL014W; date=19700101"
/controlled_curation="term=species distribution, conserved in eukaryotes; date=20081110"
/controlled_curation="term=species distribution, conserved in metazoa; date=20081110"
/controlled_curation="term=species distribution, conserved in vertebrates; date=20081110"
/controlled_curation="term=species distribution, conserved in fungi; date=20081110"
/controlled_curation="term=species distribution, conserved in archaea; date=20081110"
/controlled_curation="term=species distribution, predominantly single copy (one to one); date=20081110"

I noticed because this gene  fib1 had no "taxonomic conservation" section.

**Comment by kimrutherford** [comment] 2021-07-21 00:41
My guess is that the bug is caused by having multiple transcripts.  I'll work on it.

**Comment by kimrutherford** [comment] 2021-07-21 09:08
> caused by having multiple transcripts

It was, but it took a while to track down.  It's only a problem for annotation that should be attached to the genes (like species_dist).  The code was using /controlled_curation annotations only from one CDS when there are multiple transcripts.

It's now fixed so that you can put the /controlled_curation qualifiers on any of the CDS features.

The /GO annotations were being loading without a problem because they are transcript specific.

I'm running a test load locally and I'll also check the main nightly load in the morning.

**Comment by kimrutherford** [comment] 2021-07-22 01:50
> I'm running a test load locally and I'll also check the main nightly load in the morning.

It all looks good on the main site.

**Closed by kimrutherford** 2021-07-22 01:50 UTC
Labels: bug, needs checking
